variables:
  REPO_NAME: gitlab.com/systemz/aimpanel2

# The problem is that to be able to use go get, one needs to put
# the repository in the $GOPATH. So for example if your gitlab domain
# is gitlab.com, and that your repository is namespace/project, and
# the default GOPATH being /go, then you'd need to have your
# repository in /go/src/gitlab.com/namespace/project
# Thus, making a symbolic link corrects this.
before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
    - compile
    - build
    - deploy

frontend:
    stage: compile
    image: node:10-alpine
    script:
    - cd master-frontend
    - apk add yarn
    - yarn install --frozen-lockfile
    - VUE_APP_API_URL=https://api-lab.aimpanel.pro yarn build
    - ls -alh dist
    - mv dist $CI_PROJECT_DIR/aimpanel-master-frontend
    cache:
      key: "$CI_JOB_NAME"
      paths:
      - master-frontend/node_modules
    artifacts:
      paths:
      - aimpanel-master-frontend
      expire_in: 1 month
    only:
    - master
    - merge_requests
    tags:
    - docker

backend:
    image: golang:latest
    stage: compile
    script:
    #- go get github.com/jstemmer/go-junit-report
    - go get github.com/go-swagger/go-swagger/cmd/swagger
    - cd ./master
    - go get
    - cd ../
    - bash Taskfile.sh swagger-gen
    #- go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/aimpanel-master
    #- go fmt $(go list ./... | grep -v /vendor/)
    #- go vet $(go list ./... | grep -v /vendor/)
    #- go test -race $(go list ./... | grep -v /vendor/)
    #- go test -v 2>&1 | go-junit-report > $CI_PROJECT_DIR/report.xml
    - cd ./master
    - CGO_ENABLED=0 go build -o $CI_PROJECT_DIR/aimpanel-master
    - cd ../slave
    - go get
    - CGO_ENABLED=0 go build -o $CI_PROJECT_DIR/aimpanel-slave
    - cd $CI_PROJECT_DIR
    cache:
      key: "$CI_JOB_NAME"
      paths:
        - $GOPATH/src/github.com
    artifacts:
      #reports:
      #  junit: report.xml
      # https://docs.gitlab.com/ee/ci/yaml/README.html#artifactsreportscodequality-starter
      paths:
      - aimpanel-master
      - aimpanel-slave
      - swagger.json
      expire_in: 1 month
    only:
    - master
    - merge_requests
    tags:
    - docker

docker-images:
    stage: build
    image: docker:stable
    services:
    - docker:stable-dind
    script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --tag $CI_REGISTRY_IMAGE/frontend:pipeline-$CI_PIPELINE_ID -f frontend.Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/frontend:pipeline-$CI_PIPELINE_ID
    - docker build --tag $CI_REGISTRY_IMAGE/master:pipeline-$CI_PIPELINE_ID -f master.Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/master:pipeline-$CI_PIPELINE_ID
    - docker build --tag $CI_REGISTRY_IMAGE/slave:pipeline-$CI_PIPELINE_ID -f slave.Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/slave:pipeline-$CI_PIPELINE_ID
    only:
    - master
    - merge_requests
    tags:
    - docker

deploy:
    stage: deploy
    image: alpine:latest
    script:
    - apk add --no-cache curl
    - curl -X POST -F token=$INFRA_TOKEN -F "ref=master" -F "variables[SERVICE_NAME]=aimpanel-lab" -F "variables[SERVICE_VERSION]=pipeline-$CI_PIPELINE_ID" https://gitlab.com/api/v4/projects/6986946/trigger/pipeline
    only:
    - master