version: "3.7"
services:
  db1:
    image: docker.io/bitnami/mariadb:10.1.37
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_DATABASE=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - mariadb:/bitnami/mariadb
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:edge
    depends_on:
      - db1
    ports:
      - 8080:80
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
  redis:
    image: 'redis:5'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    volumes:
      - 'redis_data:/bitnami/redis/data'
  phpredmin:
    image: 'sasanrose/phpredmin'
    environment:
      - PHPREDMIN_DATABASE_REDIS_0_HOST=redis
    ports:
      - 8090:80
    depends_on:
      - redis
volumes:
  redis_data:
    driver: local
  mariadb:
    driver: local
  

