version: "3.7"
services:
  redis:
    image: 'redis:5-alpine'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    volumes:
      - 'redis_data:/bitnami/redis/data'
  phpredmin:
    image: 'sasanrose/phpredmin'
    environment:
      - PHPREDMIN_DATABASE_REDIS_0_HOST=redis
    ports:
      - 8090:80
    depends_on:
      - redis
  couchdb:
    image: 'couchdb:3.0.0'
    restart: always
    environment:
      - COUCHDB_USER=dev
      - COUCHDB_PASSWORD=dev
    ports:
      - 5984:5984
      - 4369:4369
      - 9100:9100
volumes:
  redis_data:
    driver: local