version: "3.7"
services:
  database:
    image: docker.io/bitnami/mariadb:10.1.37
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=dev
      - MARIADB_USER=dev
      - MARIADB_PASSWORD=dev
    ports:
      - 3306:3306
    volumes:
      - mariadb:/bitnami/mariadb
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=database
      - PMA_USER=dev
      - PMA_PASSWORD=dev
  redis:
    image: 'redis:5-alpine'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    volumes:
      - 'redis_data:/bitnami/redis/data'
  phpredmin:
    image: 'sasanrose/phpredmin'
    environment:
      - PHPREDMIN_DATABASE_REDIS_0_HOST=redis
    ports:
      - 8090:80
    depends_on:
      - redis
  couchdb:
    image: 'couchdb:2'
    restart: always
    environment:
      - COUCHDB_USER=dev
      - COUCHDB_PASSWORD=dev
    ports:
      - 5984:5984
      - 4369:4369
      - 9100:9100
volumes:
  redis_data:
    driver: local
  mariadb:
    driver: local