package main

type AutoGenerated struct {
	APIVersion string `yaml:"apiVersion"`
	Kind       string `yaml:"kind"`
	Metadata   struct {
		Name   string `yaml:"name"`
		Labels struct {
			Game    string `yaml:"game"`
			Edition string `yaml:"edition"`
			Runtime string `yaml:"runtime"`
		} `yaml:"labels"`
	} `yaml:"metadata"`
	Spec struct {
		Vars struct {
			INSTAURL string `yaml:"INSTA_URL"`
		} `yaml:"vars"`
		Resources struct {
			Memory struct {
				Min int `yaml:"min"`
				Max int `yaml:"max"`
			} `yaml:"memory"`
			CPU struct {
				Min int `yaml:"min"`
				Max int `yaml:"max"`
			} `yaml:"cpu"`
		} `yaml:"resources"`
		Features struct {
			Autorestart string `yaml:"autorestart"`
		} `yaml:"features"`
		Actions struct {
			BeforeStart []struct {
				Name string `yaml:"name"`
			} `yaml:"beforeStart"`
			BeforeRestart []struct {
				ConsoleCmd string `yaml:"consoleCmd,omitempty"`
				Sleep      struct {
					Seconds int `yaml:"seconds"`
				} `yaml:"sleep,omitempty"`
				Webhook struct {
					Discord string `yaml:"discord"`
				} `yaml:"webhook,omitempty"`
			} `yaml:"beforeRestart"`
			BeforeStopOrRestart struct {
				BeforeStop struct {
					Sync struct {
						TimeLimit struct {
							Seconds int `yaml:"seconds"`
						} `yaml:"timeLimit"`
					} `yaml:"sync"`
				} `yaml:"beforeStop"`
			} `yaml:"beforeStopOrRestart"`
			AfterStart       interface{} `yaml:"afterStart"`
			AfterCrash       interface{} `yaml:"afterCrash"`
			AfterAutoRestart []struct {
				Pushover struct {
					Msg   interface{} `yaml:"msg"`
					Title interface{} `yaml:"title"`
					Sound interface{} `yaml:"sound"`
				} `yaml:"pushover"`
			} `yaml:"afterAutoRestart"`
			AfterResurrection interface{} `yaml:"afterResurrection"`
		} `yaml:"actions"`
		Schedule []struct {
			Name       string `yaml:"name"`
			Cron       string `yaml:"cron"`
			ConsoleCmd string `yaml:"consoleCmd"`
		} `yaml:"schedule"`
		Container struct {
			Image   string   `yaml:"image"`
			Command []string `yaml:"command"`
			Args    []string `yaml:"args"`
		} `yaml:"container"`
		HealthCheck struct {
			Interval int    `yaml:"interval"`
			Method   string `yaml:"method"`
			Port     string `yaml:"port"`
		} `yaml:"healthCheck"`
		Network struct {
			Ports []struct {
				Protocol string `yaml:"protocol"`
				Internal int    `yaml:"internal"`
				External int    `yaml:"external"`
			} `yaml:"ports"`
		} `yaml:"network"`
	} `yaml:"spec"`
}
