version: "2"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
    volumes:
      - cabbage-postgre-data:/var/lib/postgresql/data/
  redis:
    image: redis
    ports:
      - "6379:6379"
  redis-admin:
    image: rediscommander/redis-commander
    ports:
      - "6380:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
volumes:
  cabbage-postgre-data:
