export interface Host {
  id: string,
  name: string,
  user_id: string,
  ip: string,
  token: string,
  metric_frequency: string,
  os: string,
  platform: string,
  platform_family: string,
  platform_version: string,
  kernel_version: string,
  kernel_arch: string,
  state: number,
  created_at: Date,
}

export interface Metric {
  _id: string,
  host_id: string,
  cpu_usage: number,
  ram_free: number,
  ram_total: number,
  ram_used: number,
  disk_free: number,
  disk_used: number,
  disk_total: number,
  user: number,
  system: number,
  idle: number,
  nice: number,
  iowait: number,
  irq: number,
  softirq: number,
  steal: number,
  guest: number,
  guest_nice: number,
  created_at: Date,
  avg: number,
  t: number,
}
